"""Human-readable placeholders when external API fields are absent."""

NO_TITLE = "No event title available"
NO_TIME = "No time data available"
NO_DATE = "No date data available"
NO_VENUE = "No venue data available"
NO_LOCATION = "No location data available"
NO_DISTANCE = "No distance data available"
NO_PRICE = "No price data available"
NO_CATEGORY = "No category data available"
NO_DESCRIPTION = "No description available"
NO_IMAGE = "No image available"
NO_TAG = "No tag data available"
NO_LINEUP = "No lineup data available"
NO_TICKET = "No ticket data available"
NO_TICKET_TYPE = "No ticket type available"
